# Generated by Django 3.0.6 on 2020-06-12 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postres', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechapedido', models.DateField()),
                ('fechaentrega', models.DateField()),
                ('fechaenvio', models.DateField()),
                ('formaenvio', models.CharField(max_length=50)),
                ('destinatario', models.CharField(max_length=70)),
                ('direcciondestinatario', models.TextField()),
                ('ciudaddestinatario', models.CharField(max_length=70)),
                ('clientes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Clientes')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iva', models.IntegerField(blank=True, choices=[(0, 0), (19, 19)], default=19, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('descuento', models.IntegerField(blank=True, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.Pedidos')),
                ('postre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postres.Postres')),
            ],
        ),
    ]
